
services:
  # Define the service name
  app:
    # Define the image that we want to use
    image: acorn:latest
    # Expose the port that the app is running on, for
    # easier debugging than going through nginx
    ports:
      - "2554:2554"
    # Define the networks that we want to use
    networks:
      - acornnet
    # For hot deploy of code ... NOT FOR PRODUCTION!
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: .

  # The mongodb database service
  db:
    # Define the image that we want to use
    image: mongo:latest
    # Define the name so we can reference it
    container_name: acorn-mongo
    # Define the volumes that we want to mount
    volumes:
      - acornvol:/data/db
    # Define the networks that we want to use
    networks:
      - acornnet

# Define the networks that we want to use
networks:
  acornnet:
    driver: bridge

# Define the volumes that we want to use
volumes:
  acornvol:
      driver: local
